[package]
name = "pcd-transformer"
version.workspace = true
edition = "2021"

[dependencies]
pcd-core = { path = "../pcd-core" }
projection-transform = { path = "../projection-transform" }

[dev-dependencies]
pcd-parser = { path = "../pcd-parser" }
pcd-exporter = { path = "../pcd-exporter" }
